[project]
name = "app-agendamento"
version = "0.1.0"
description = "app de agendamento entre usuarios e colaboradores"
authors = [
    {name = "Lord_Doug"}
]
license = {text = "mit"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.1.1,<7.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "psycopg[binary] (>=3.3.6,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]

