# Generated by Django 6.1.1 on 2026-10-05 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_type', models.CharField(choices=[('recepcao', 'Recepção'), ('central', 'Central de Atendimento'), ('profissional', 'Profissional')], max_length=20, verbose_name='tipo solicitado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='inicio')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('interval', models.PositiveIntegerField(default=30, verbose_name='intervalo(min)')),
                ('recurring', models.BooleanField(default=False, verbose_name='semanal')),
                ('day_week', models.PositiveSmallIntegerField(default=0)),
                ('professional', models.ForeignKey(limit_choices_to={'groups__name': 'profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Atendido', 'Atendido'), ('Ausente', 'Ausente'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20)),
                ('num_reschedules', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(limit_choices_to={'groups__name': 'profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
